version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "80:5000"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword123
      MARIADB_DATABASE: myportfoliodb
      MARIADB_USER: myportfolio
      MARIADB_PASSWORD: Mypassword123!
    volumes:
      - mydatabase:/var/lib/mysql

volumes:
  mydatabase:
