name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    env:
      TESTING: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # You can change this to 3.10 if your app needs it

      - name: Setup Python Virtual Environment
        run: python -m venv venv #python3-virtualenv

      - name: Install Dependencies
        run: venv/bin/pip install -r requirements.txt #python3-virtualenv

      - name: Make run_test.sh executable
        run: chmod +x run_test.sh

      - name: Run Tests
        run: ./run_test.sh
